name: Commit date to main branch
on: workflow_dispatch
permissions:
  contents: write
jobs:
  commit-date:
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch
      - name: checkout
        uses: actions/checkout@v2
        with:
          token: ${{secrets.GHPAT}}

      - name: save current date
        run: |
          # do some operation that changes a file in the git repo
          date > ./.github/workflows/time.txt

      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: commit
        run: |
          # Stage the file, commit and push
          git add ./.github/workflows/time.txt
          git commit -m "new date commit"
          git push origin main
